### ISSUE TITLE
Toggle tree mode

### ISSUE THREAD

**Issue by themanifold** [tomasbonco/gitlabtree#1]
You might want to consider adding an option to toggle the tree mode on or off.

Great tool, by the way.

**Comment by tomasbonco** [comment]
Hello,

Thank you for your kind words :) Do you mean turning whole plugin on and off, or whether folders should be expanded (or closed) by default?

**Comment by themanifold** [comment]
Hello,

Thanks for getting back to me. I mean both, really. :)

**Comment by tomasbonco** [comment]
Ok, I'll see what I can do.

**Comment by tomasbonco** [comment]
Thank you very much for requesting this. I was thinking for a usage scenario for this one, then I found it.
I have implemented it, hope you'll like it.

It was released today in version 1.0.0.
More info about release: https://github.com/tomasbonco/gitlabtree/releases/tag/v1.0.0
