### ISSUE TITLE
[Request] Adjust Width of Tree Menu

### ISSUE THREAD

**Issue by controllerface** [tomasbonco/gitlabtree#14]
Love this extension already, making migrating from Bitbucket a lot easier. Would love to able to adjust the width of the tree menu. It wouldn't even need to be dynamically resize-able necessarily, just an option in the Chrome extension menu to set the width of the box would be great.

**Comment by tomasbonco** [comment]
Would you like to have it more narrow or wider?
I understand the use case, but I don't see this as a priority. So I'm keeping this open.

**Comment by controllerface** [comment]
I find that I generally wish it was wider. I realize different people probably would have different preferences so the thought of it being configurable in the chrome extension just made sense to me.

**Comment by tomasbonco** [comment]
This was finally implemented and released with v1.0.0 (today).
Thank you for reporting this.

More info: https://github.com/tomasbonco/gitlabtree/releases/tag/v1.0.0
