### ISSUE TITLE
Collapse folder chains into a single node

### ISSUE THREAD

**Issue by JanecekPetr** [tomasbonco/gitlabtree#15]
In _some_ (ehm, Java) languages, it is common to have code separated by packages that are a fairly deep folder structure, often in the form of `com.github.janecekpetr.projectname.packagename`...

This is what happens then: https://i.imgur.com/u2BOlmV.png (sorry for lots of blur, this is my work's code)

I'm asking for collapsing the whole main/java/com/.../.../util structure (all folders containing no changes, just another folder) under a single node so that it does not take so much vertical space, and does not indent the actual filenames so much (preserving the horizontal space as well).

**Comment by tomasbonco** [comment]
This is great request. I will implement it.

**Comment by tomasbonco** [comment]
Thank you very much for this request. I implemented it and released with version 1.0.0. Let me know if it works :)

More info about v1.0.0: https://github.com/tomasbonco/gitlabtree/releases/tag/v1.0.0
