### ISSUE TITLE
Does not work with GitLab CE 11

### ISSUE THREAD

**Issue by d3dave** [tomasbonco/gitlabtree#16]
1. Changed files list contains a hidden element with inline style instead of `.hidden` class.
2. Width is not adjusted according to window width.
3. Every time a changed file is selected, the window scrolls a bit upwards.

**Comment by tomasbonco** [comment]
Thank you for reporting this.

**Comment by tomasbonco** [comment]
1. Fixed by v0.0.11

Releasing fast so devs can work during tomorrow. Rest will be part of the more significant update, that I'm currently working on.

I'm closing this one, as the title issue is fixed. But will comment again, once the rest implemented as well.

**Comment by gburiola** [comment]
Hey @tomasbonco. 

First of all, thanks for this great extension.

After the update to gitlabtree 0.11, the diff panel is too narrow and no longer adjusts with the screen width. It's always fixed with 693p width.

If I switch between inline and side-by-side, then it adjusts to screen width.

**Comment by tomasbonco** [comment]
Hi!

It it’s not an issue with plugin itself but Gitlab 11.1. I am aware of this situation, and the fix will be implemented in the upcoming more significant update coming with new features.

More detailed explanation:
Gitlab adds a ‘narrow’ class to a div where the plugin is rendered to. So the fix actually will have to either remove such class or suppress it.

Lastly, I want to thank you, for your kind words as well as reporting unpleasant  behaviour.

**Comment by tomasbonco** [comment]
Hi guys. I fixed the issue, plugin being too narrow. Thank you for reporting it.
More info about the release: https://github.com/tomasbonco/gitlabtree/releases/tag/v1.0.0

**Comment by gburiola** [comment]
Latest changes are amazing !!! 

Thanks for the great work Tomáš !!!
