### ISSUE TITLE
How to make this work ?

### ISSUE THREAD

**Issue by tungdt-90** [tomasbonco/gitlabtree#19]
We use Gitlab Enterprise ver 11, and after I install this extension, nothing happens.

I don't see anything that looks like the picture, and there isn't any setup document anywhere. 

So, do I need any extra steps to make it works? Or it just simply incompatible with Gitlab version 11?

**Comment by tomasbonco** [comment]
Hi! Thank you very much for reporting this. Others might struggle as well.
The extension is always compatible with latest GitLab and a few versions backward. There are no more extra steps required than installing.

I was thinking a bit, and these are possible reasons:
1. **You are using self-hosted GitLab, and you are missing requested header**
The extension uses `meta[content="GitLab"]` selector to determine whether the page it is looking at is GitLab instance. I hoped it's going to be sufficient, but I might be wrong. If you open a Debug Tools in a browser (CTRL + SHIFT + I), can you found under `<head>` section `<meta>` element that has as an attribute `content="GitLab"`? If not, can you please send me a screenshot of your `<head >` structure, so I'll find another selector?

2. **Extension failed for some reason**
Being in Debug Mode of the browser, switch to `Console` tab and change the frame from `top` to `GitLab - Tree view for code` (it is in the top-left corner, second row). Can you now please verify that there are no errors in the console?

3. **You are not looking at source code**
The extension only works on Merge Requests or when looking at Commits. 

If you need further help with instructions, just let me know I'll provide a step-by-step tutorial (what browser are you using?).

**Comment by tungdt-90** [comment]
Thank you for your reply, I can confirm that your **1** and **2** are correct. Because I was expecting it to be able to function just like Octotree, so I did not notice that this only work on Merge Requests or Commits.

**Comment by tomasbonco** [comment]
Enjoy! :)

**Comment by schmidan** [comment]
uuuh, 
> You are not looking at source code
> The extension only works on Merge Requests or when looking at Commits.

a little note about this on the front (readme) page would be very helpful i guess ;)

i was under the impression i could browse the whole code base just like octotree as well

**Comment by tomasbonco** [comment]
Thank you for feedback. I’ll add it there.
