### ISSUE TITLE
The latest modifications broke the extension?

### ISSUE THREAD

**Issue by thiagotalma** [tomasbonco/gitlabtree#2]
Last week Gitlab made some modifications to the file list.

The extension broke?

**Comment by PierreVincent** [comment]
I'm seeing this as well, it looks like the extension no longer works with GitLab 9.5.

**Comment by tomasbonco** [comment]
Thank you very much for reporting. I'll try to fix ASAP.

**Comment by tomasbonco** [comment]
Ok, I just released v0.0.7 addressing this issue, so tomorrow it should be working :) (let me know if it doesn't)

**Comment by PierreVincent** [comment]
Looks good - working fine for me now. Thanks Tomáš for the quick fix!

**Comment by yeyulei** [comment]
![image](https://user-images.githubusercontent.com/32812519/31591689-7fca1510-b254-11e7-984b-03bad591706a.png)

怎么使用的？我再附件组件里面添加的，然后就登录gitlab服务器刷新，没有树结构。

**Comment by tomasbonco** [comment]
Closing this one, because fix was verified.
@yeyulei Please fill new issue, but generally, you will see plugin working during Merge Requests or when you look into commits and so on. The plugin works with files, not repos.
