### ISSUE TITLE
can't run `yarn build`

### ISSUE THREAD

**Issue by KentonYu** [tomasbonco/gitlabtree#24]
![image](https://user-images.githubusercontent.com/11837283/46242731-bcb6b480-c3fe-11e8-8981-0f5312306877.png)

**Comment by tomasbonco** [comment]
It looks like it's not parsing TypeScript, but trying to parse Javascript instead. As far as I know, parcel should auto-detect it. Can you verify that the problem is present when you use `npm`?

**Comment by KentonYu** [comment]
![image](https://user-images.githubusercontent.com/11837283/46242997-98a8a280-c401-11e8-8188-7b8285971726.png)
use npm also have the same problem，sad QAQ

**Comment by tomasbonco** [comment]
Thank you very much for this.
