### ISSUE TITLE
Not working with Firefox 57 and Gitlab-CE 10.3.2

### ISSUE THREAD

**Issue by s4msung** [tomasbonco/gitlabtree#3]
This Plugins does not work anymore with Firefox 57 and Gitlab-CE 10.3.2

**Comment by tomasbonco** [comment]
Thank you very much for reporting. I also tested it on Chrome and it didn't work either. Further investigation showed that it is because in the new version of Gitlab they changed the structure of the list containing changed files. Hopefully fix will be ready in 24h.

**Comment by tomasbonco** [comment]
Fixed in: d91b0dc3d6f96c8639e85e9db98aeddbb4485ab7
Rolling changes.

**Comment by tomasbonco** [comment]
Released v0.0.8 fixing this issue. For Chrome users, it might be available in an hour. For Firefox and Opera users it might take longer because they do a review. Hopefully, in less than 3 days you should see changes :)

Thank you one more time for reporting!

**Comment by s4msung** [comment]
Update for Gitlab to 10.3.3 this morning fixed the issue for me on Firefox 57.0.3

Maybe Gitlab fixed something related to that in 10.3.3?

**Comment by tomasbonco** [comment]
Mozilla approved v0.0.8 at 12AM UTC, and Opera at 2PM UTC (pretty fast this time), so I believe what you saw was updated version of extension :)
