### ISSUE TITLE
Make available on Repository/Files

### ISSUE THREAD

**Issue by leocaseiro** [tomasbonco/gitlabtree#4]
Hi @tomasbonco, thank you so much for this awesome extension.

I only can see the Source Tree on commits. That would be nice to use in any source/file navigating inside the Repository/Files similar what [octotree](https://github.com/buunguyen/octotree) does.

Thanks

**Comment by tomasbonco** [comment]
Hi!
The major goal of this extension is to help you understand and easily navigate thru commits (or merge requests). It is based on scraping HTML already loaded (so there no additional API calls). Adding ability to use folder structure for repository/files seems pretty difficult (= time consuming, as it is completely different approach). At the moment I'm focusing on keeping it lean so I can quickly update extension once inconsistency with Gitlab appears (usually when Gitlab changes HTML structure after update).

That being said, I'm sorry, but I can only recommend you to use both extensions at the same time (if that works). I'll keep an eye on this issue, and if this becomes requested feature by a greater audience, I'll implement it. (So if you are not @leocaseiro and you really really want this feature, add like or comment.)

Have a nice day and thank you for using my extension.

**Comment by leocaseiro** [comment]
Hi @tomasbonco. Thank you for your reply.

Unfortunately the octotree doesn't work on gitlab, only on github.

I understand is harder work than not using API. I wasn't aware you were reading the loaded files. You are pretty smart and good.

For the time being, I'll be hoping that [gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/13723) is going to release something like that [soon](https://gitlab.com/gitlab-org/gitlab-ce/issues/38011).

Many Many thanks.

**Comment by leocaseiro** [comment]
UPDATE: I found an alternative extension that works for gitlab: 
https://chrome.google.com/webstore/detail/gitlab-code-view/gglalfcdiahpedikbmegmmkmpmajnpjj

**Comment by tomasbonco** [comment]
Good!

I'm closing this one. If any news, updates, requests feel free to open it :)
