### ISSUE TITLE
Scroll to top when switching between files

### ISSUE THREAD

**Issue by zyrorl** [tomasbonco/gitlabtree#6]
It would be really great and improve usability if scrolling to top  after switching files.

**Comment by tomasbonco** [comment]
Hi, what browser do you use?

**Comment by sl33kr** [comment]
We are seeing an issue using version 1.0.0 in Chrome 68.0.3440.106 where clicking a file scrolls the window up slightly with each change.

**Comment by sl33kr** [comment]
Same behaviour in Firefox 61.0.2

**Comment by tomasbonco** [comment]
Fix was released.
