### ISSUE TITLE
[Feature request] Don't show the panel when there is a single file

### ISSUE THREAD

**Issue by seqizz** [tomasbonco/gitlabtree#8]
First of all, nice extension. Relaxed my mind while checking MR's.

I guess it's pretty unnecessary if I have changes only 1 file, since it's path is clearly shown on the top of the diff block.

**Comment by tomasbonco** [comment]
Hi, thank you very much for your kind words.

What would be the benefit, because I'm checking the panel first to see how many files were changed?

**Comment by seqizz** [comment]
Feels like it steals screen width for no reason, since new Gitlab navigation is also using the side panel on left. We're getting a valuable area just to show 1 file name, which is apparent on the screen anyway. This is particularly disturbing while using side by side diff view. Please check following screenshot:
![Example](https://i.imgur.com/iw4p2n1.jpg)
The area (marked with green) has given away, just because to see single file path, which is already a duplicate (marked with red).

// Edit: I got your concern also. But showing no panel could only indicate "there is nothing to show except this file" to me. Of course everyone might get different :)

**Comment by tomasbonco** [comment]
I see. Sometimes Gitlab updates it's system and missing panel is a good indicator extension is broken.
I'm right now very tight on free time, but I will definetely explore possibilities of moving/hiding panel, once I'll have some. I will keep this open.

**Comment by seqizz** [comment]
Thanks, I have zero experience on this but I'll also try to place the tree inside the left sidebar (if possible).

**Comment by tomasbonco** [comment]
This was finally implemented and released with v1.0.0 (today).
Thank you for reporting this.

More info: https://github.com/tomasbonco/gitlabtree/releases/tag/v1.0.0
